schema = 3

[mod]
  [mod.'filippo.io/age']
    version = 'v1.3.1'
    hash = 'sha256-Qs/q3zQYV0PukABBPf/aU5V1oOhw95NG6K301VYJk8A='

  [mod.'filippo.io/hpke']
    version = 'v0.4.0'
    hash = 'sha256-xKPT2hMzz/i3xdDK3NKn6FOmfQPxIMgxCOmm8U1heY4='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.14.0'
    hash = 'sha256-d+zcIobMS5Y0/Ym9Uxubf20uyw0aBCr0f1oEOAGHlEA='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/charmbracelet/bubbles']
    version = 'v1.0.0'
    hash = 'sha256-Vz9QgctlzJqggPwfi48Lbn38ZJXu3Y71byp5uuuzUvU='

  [mod.'github.com/charmbracelet/bubbletea']
    version = 'v1.3.10'
    hash = 'sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.1'
    hash = 'sha256-d/NjM/ybG+bGRRRMMcjbPCFGFS5noZRMaL05Ix5r/II='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.1-0.20250404203927-76690c660834'
    hash = 'sha256-CwS1AyoRsPOFA4SrC0CTtwLnbg57FmmSW/mvVQUFYcc='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.6'
    hash = 'sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.15'
    hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.9.0'
    hash = 'sha256-9CNyTZPSncKQ7Y0my9DR4WYXDjtDHYNL512D691WDAM='

  [mod.'github.com/clipperhouse/stringish']
    version = 'v0.1.1'
    hash = 'sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.5.0'
    hash = 'sha256-Men4JLhiuEtAx8ZSzId5ciRWhud68o3k/B48ppwyxkM='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.11.0'
    hash = 'sha256-iXBBgykYu9Dcd+7LMJyRYc3Ry47jmuLGZFW13zU6toU='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/erikgeiser/coninput']
    version = 'v0.0.0-20211004153227-1c3628e74d0f'
    hash = 'sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU='

  [mod.'github.com/fxamacker/cbor/v2']
    version = 'v2.9.0'
    hash = 'sha256-/IZK76MRCrz9XCiilieH5tKaLnIWyPJhwxDoVKB8dFc='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/hanwen/go-fuse/v2']
    version = 'v2.9.0'
    hash = 'sha256-6rCuUaTMqKmcCAldrc/0p+Cpru0YTUaqDPw4gX2Mek8='

  [mod.'github.com/junegunn/fzf']
    version = 'v0.67.0'
    hash = 'sha256-sHEnon8xm9EniEtjhPoJSp9f4COmQleoxJ4T3SI0Hzg='

  [mod.'github.com/klauspost/compress']
    version = 'v1.18.4'
    hash = 'sha256-swwNE6xKz4ZAOUHPWFlHYiqFeZLRZuuKYhLQ34aYnAU='

  [mod.'github.com/klauspost/cpuid/v2']
    version = 'v2.0.12'
    hash = 'sha256-I+vhA+VCfEa26VpukkuOQhfT2/+hpReAHqdyJFyoLCw='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-localereader']
    version = 'v0.0.1'
    hash = 'sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.19'
    hash = 'sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE='

  [mod.'github.com/muesli/ansi']
    version = 'v0.0.0-20230316100256-276c6243b2f6'
    hash = 'sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v0.1.9'
    hash = 'sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY='

  [mod.'github.com/pierrec/lz4/v4']
    version = 'v4.1.25'
    hash = 'sha256-rpGrxdd36HU2aFtYjLET24v9qmqexkhCGwfPGGRoId0='

  [mod.'github.com/pion/datachannel']
    version = 'v1.6.0'
    hash = 'sha256-OmLcEuTipeNzQ/0jlE8FGWN3qEw4BPrewF7XtnmUuq4='

  [mod.'github.com/pion/dtls/v3']
    version = 'v3.1.2'
    hash = 'sha256-eWgXdBDNk/9Tpi5M5dEq0lAWYWU+tbnDUVaiQyQTjFU='

  [mod.'github.com/pion/ice/v4']
    version = 'v4.2.1'
    hash = 'sha256-pTauUsr06+I5ObphcwpLJjCv/E1+ML5I78lHit+eTxk='

  [mod.'github.com/pion/interceptor']
    version = 'v0.1.44'
    hash = 'sha256-DI+DxT/fz311v/P6kXrzk8TbBau8fA4oVw7GOlQu9jw='

  [mod.'github.com/pion/logging']
    version = 'v0.2.4'
    hash = 'sha256-S3bPblOkgYbRnbuC0YVTGUh3aCdaIHEQyoK+suhwYxk='

  [mod.'github.com/pion/mdns/v2']
    version = 'v2.1.0'
    hash = 'sha256-eBnhv1uCXVouZF2ztfkCLqDOojrc8Hsnk84P4fJSSQk='

  [mod.'github.com/pion/randutil']
    version = 'v0.1.0'
    hash = 'sha256-jl6WfLPH7RV5MQhQtqwSDzhIL0D0eCnDT2L9uButveI='

  [mod.'github.com/pion/rtcp']
    version = 'v1.2.16'
    hash = 'sha256-Ix+zFe8E9TbuAS/oiacIcVOm8DVmauLPyYac5I9UC6U='

  [mod.'github.com/pion/rtp']
    version = 'v1.10.1'
    hash = 'sha256-ALAopoUYHwc411LNZy1R3jZ7k42sfNQ1qFCkfT6ndU8='

  [mod.'github.com/pion/sctp']
    version = 'v1.9.2'
    hash = 'sha256-xmT2mun0G3nnp958QpmQJYi6u7TkrQN9fgOEOe/5PXI='

  [mod.'github.com/pion/sdp/v3']
    version = 'v3.0.18'
    hash = 'sha256-xY20o+lpAq3CS4V/OKpgkCGrkZtF7Uz+3KnLuMh4Lzk='

  [mod.'github.com/pion/srtp/v3']
    version = 'v3.0.10'
    hash = 'sha256-QFO2Jnm2qaOC5HfmoEK74krncLdBzEbApH4TELskN+U='

  [mod.'github.com/pion/stun/v3']
    version = 'v3.1.1'
    hash = 'sha256-RsBz18rPiiVo4133WFOqmgl7Mz8SD3EZhhoF6n+Og/s='

  [mod.'github.com/pion/transport/v4']
    version = 'v4.0.1'
    hash = 'sha256-hDHt5UUtdVB6EQuWjIg1s5PPyUTq2gY5sUpydVe87Ak='

  [mod.'github.com/pion/turn/v4']
    version = 'v4.1.4'
    hash = 'sha256-S7QpWX9WnVarnfyzHp+YYtPbfPyav3YhQ6sa6nAlm/Q='

  [mod.'github.com/pion/webrtc/v4']
    version = 'v4.2.9'
    hash = 'sha256-3RUi41Qqk2VWKvPzkf9zdo7eEVB7HOC+CNCa0fE0TDo='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/tidwall/jsonc']
    version = 'v0.3.2'
    hash = 'sha256-lelWNZLQDQs3BSi1kwrpa4mVKJ6eU2qGXVIOi247JRw='

  [mod.'github.com/wlynxg/anet']
    version = 'v0.0.5'
    hash = 'sha256-F4JBxnY/O08YIwtjaMqEm0AV/fx42SeS7uGUhZHoQyc='

  [mod.'github.com/x448/float16']
    version = 'v0.8.4'
    hash = 'sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.7.8'
    hash = 'sha256-SNJMPPiXkRDLVOldrHN0ErC3bUB2VoWaLDkd9zmMATw='

  [mod.'github.com/zeebo/blake3']
    version = 'v0.2.4'
    hash = 'sha256-Q8KSVhnSR1cwfTp4LkPdfI1UWWkDDHa9fslNsa3Qfo8='

  [mod.'golang.org/x/crypto']
    version = 'v0.48.0'
    hash = 'sha256-uBIGGSGmWWklRxX6XTOqUECzz165UFY9Y99Ka3pLKAw='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20250408133849-7e4ce0ab07d0'
    hash = 'sha256-Lw/WupSM8gcq0JzPSAaBqj9l1uZ68ANhaIaQzPhRpy8='

  [mod.'golang.org/x/net']
    version = 'v0.50.0'
    hash = 'sha256-A3tvRuVotO4d8S1FX9ri9CpMJacrFJmHebLJ5m9b+Ss='

  [mod.'golang.org/x/sys']
    version = 'v0.41.0'
    hash = 'sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk='

  [mod.'golang.org/x/term']
    version = 'v0.40.0'
    hash = 'sha256-tu8USqDmcWfwery/+xti/BdUpNLbMNmZeghBNDsj1fQ='

  [mod.'golang.org/x/text']
    version = 'v0.34.0'
    hash = 'sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM='

  [mod.'golang.org/x/time']
    version = 'v0.10.0'
    hash = 'sha256-vnlAME3gDR6R4cbCmSYAlR1Rjc0yUpkufTOPNvCdf6Q='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'modernc.org/libc']
    version = 'v1.65.7'
    hash = 'sha256-eqVNMdDc0tJOhWoC+MW7gy6/EWsf+m44AEx/d2/wWlY='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.11.0'
    hash = 'sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM='

  [mod.'modernc.org/sqlite']
    version = 'v1.37.1'
    hash = 'sha256-5U8KDHnzYmUXbXJfre9blEBRWlRG4BOAUEmNBPsXMaQ='

  [mod.'zombiezen.com/go/sqlite']
    version = 'v1.4.2'
    hash = 'sha256-4bZY0TEkGDfwPH6j5TaLZarY3ZLjQkYKsjKY+Cj9fjk='
